name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-quotes
        # stop the build if there are flake8 errors
        flake8 . --count --show-source --statistics --inline-quotes=double
    - name: Lint with mypy
      run: |
        pip install mypy
        mypy . --show-error-context
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
