name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt
    - name: Lint with flake8
      run: |
        pip install -r requirements/dev.txt
        # stop the build if there are flake8 errors
        flake8 . --config=setup.cfg --count --show-source --statistics
    - name: Lint with mypy
      run: |
        mypy . --config-file setup.cfg --show-error-context
    - name: Test with pytest
      run: |
        pytest
